site_name: CLS Docs
site_url: https://cls.readthedocs.io/en/latest/

markdown_extensions:
  - smarty
  - extra
  - toc
  - nl2br
  - admonition

nav:
  - ./index.md
  - 'Tutorial':
    - ./Tutorial.md
    - ./Tutorial2.md
  - 'Reference':
    - ./Quick-Ref.md
    - ./Special-Sections.md
    - ./Export-Section.md
    - ./Elements-and-Properties.md
    - ./Briks.md
    - ./Glossary.md
  - 'Technical Stuff':
    - ./Syntax.md
    - ./changelog.md
  - 'Home Page': 'https://codlark.itch.io/cls'

theme:
  name: readthedocs
  highlightjs: false