site_name: CLS Docs
site_url: https://cls.readthedocs.io/en/latest/

markdown_extensions:
  - smarty
  - extra
  - toc
  - nl2br
  - admonition

nav:
  - ./index.md
  - 'Tutorials':
    - ./Tutorial.md
    - ./Tutorial2.md
    - ./Tutorial3.md
  - 'Reference':
    - ./Quick-Ref.md
    - ./Special-Sections.md
    - ./Export-Section.md
    - ./Elements-and-Properties.md
    - ./Macros.md
    - ./Glossary.md
  - 'Technical Stuff':
    - ./Syntax.md
    - ./changelog.md
  - 'Links':
    - 'Home Page': 'https://codlark.itch.io/cls'
    - 'VS Code Extension': 'https://marketplace.visualstudio.com/items?itemName=codlark.CLS-vscode'

theme:
  name: readthedocs
  highlightjs: false